### ISSUE TITLE
Future Plans - 2022.08

### ISSUE THREAD

**Issue by katorly** [katorlys/StarlinUtils#6]
- [x] Add hover text to `/help`
- [ ] Restore `monthly.yml` & `timedata.yml` in database form instead of yaml files

More expected functions can be promoted just by commenting under this issue. @Hailaylin

**Comment by Hailaylin** [comment]
login ？such as authme， user have the same id in a discuss web site …… but have not 用 (doge

**Comment by katorly** [comment]
> login ？such as authme， user have the same id in a discuss web site …… but have not 用 (doge

U wanna require users to register on that forum before they get into the server?  
是想要让用户在进入服务器之前先在论坛上注册吗？

**Comment by Hailaylin** [comment]
所以暂时没卵用

**Comment by katorly** [comment]
#5

**Comment by katorly** [comment]
未来计划已分为以下几个部分，并且可开新的 issue 计划更多功能。
- #10 
- #11 
- #12 
- #13 

插件已经切换到 Kotlin，为了能够使用 [Taboolib](https://tabooproject.org) 提供的方便快捷的数据库操作等等。  
@Hailaylin Kotlin 是基于 Java 且相通的，有空可以了解一下 😃
